apiVersion: apps/v1
kind: Deployment
metadata:
  name: kittea-bot
spec:
  selector:
    matchLabels:
      app: kittea-bot
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kittea-bot
    spec:
      imagePullSecrets:
      - name: harbor-bot
      containers:
      - image: tale.me/bots/kittea
        name: kittea-bot
        env:
        - name: MC_EMAIL
          valueFrom:
            secretKeyRef:
              name: kittea-bot-credentials
              key: MC_EMAIL
        - name: MC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kittea-bot-credentials
              key: MC_PASSWORD
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: kittea-bot-credentials
              key: DISCORD_TOKEN
        - name: DISCORD_CHAT_CHANNEL
          valueFrom:
            secretKeyRef:
              name: kittea-bot-credentials
              key: DISCORD_CHAT_CHANNEL
        - name: DISCORD_NOTIFY_CHANNEL
          valueFrom:
            secretKeyRef:
              name: kittea-bot-credentials
              key: DISCORD_NOTIFY_CHANNEL
