version: '3'

tasks:
  dev:
    desc: 'Hot-reloading local Docker environment'
    cmds:
      - cmd: docker-compose -f docker/docker-compose.yaml -p kittea up --build
        silent: true

  clean:
    desc: 'Clean the local Docker environment'
    cmds:
      - cmd: docker rm -f kittea-bot
        silent: true

  build:
    desc: 'Build and publish the latest Docker image'
    cmds:
      - cmd: docker buildx create --name kittea-bot-builder
        silent: true
      - cmd: docker buildx use kittea-bot-builder
        silent: true
      - cmd: docker buildx build --push -t us-east4-docker.pkg.dev/aarnavtale/web/kittea -f docker/Dockerfile.prod --platform linux/amd64 --build-arg BUILD_DATE=$(date --rfc-3339=date) --build-arg GIT_STATE=$(git rev-parse HEAD) .
        silent: true
      - defer: docker buildx rm kittea-bot-builder
        silent: true
