version: '3.8'
services:
  bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: kittea-bot
    volumes:
      - ../src:/app/src
    environment:
      NODE_ENV: development
      MC_EMAIL: <microsoft-email>
      MC_PASSWORD: <microsoft-password>
      DISCORD_TOKEN: <bot-token>
      DISCORD_CHANNEL: <chat-channel>

