apiVersion: apps/v1
kind: Deployment
metadata:
  name: kittea-bot
spec:
  selector:
    matchLabels:
      app: kittea-bot
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kittea-bot
    spec:
      containers:
      - image: tale.io/state/kittea-bot
        name: kittea-bot
        env:
        - name: MC_EMAIL
          value: xmilano-21x@hotmail.com
        - name: MC_PASSWORD
          value: theseareMYSFAs
        - name: DISCORD_TOKEN
          value: ODUxODYzMjQ0Nzc1NjIwNjQ4.YL-deA.6A1GQpEi4u6KvVV0nL662UybCrU
        - name: DISCORD_CHANNEL
          value: '867137370145685505'
